apiVersion: apps/v1
kind: Deployment
metadata:
  name: apache-deployment-green
  labels:
    app: apache
    version: green
spec:
  replicas: 1
  selector:
    matchLabels:
      app: apache
      version: green
  template:
    metadata:
      labels:
        app: apache
        version: green
    spec:
      containers:
      - name: apache-container
        image: amit1159/green
        ports:
        - containerPort: 80
