apiVersion: apps/v1
kind: Deployment
metadata:
  name: apache-deployment-blue
  labels:
    app: apache
    version: blue
spec:
  replicas: 1
  selector:
    matchLabels:
      app: apache
      version: blue
  template:
    metadata:
      labels:
        app: apache
        version: blue
    spec:
      containers:
      - name: apache-container
        image: amit1159/blue
        ports:
        - containerPort: 80
