apiVersion: v1
kind: Service
metadata:
  name: apache-service
spec:
  type: LoadBalancer
  selector:
    app: apache
    version: blue  # Default version, Jenkins will patch this dynamically
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
